#!/bin/bash

# EmailJS Integration Setup Script
# This script helps set up EmailJS integration for the Hall Booking System

echo "🚀 EmailJS Integration Setup for Hall Booking System"
echo "=================================================="

# Check if .env file exists
if [ ! -f ".env" ]; then
    echo "📝 Creating .env file from template..."
    cp env.example .env
    echo "✅ .env file created. Please edit it with your actual values."
else
    echo "✅ .env file already exists."
fi

echo ""
echo "📋 Next Steps:"
echo "=============="
echo ""
echo "1. 📧 Create EmailJS Account:"
echo "   - Go to https://www.emailjs.com"
echo "   - Sign up for a free account"
echo "   - Verify your email address"
echo ""
echo "2. 🔧 Set up Email Service:"
echo "   - Go to Email Services in your dashboard"
echo "   - Add your email service (Gmail, Outlook, etc.)"
echo "   - Note down your Service ID"
echo ""
echo "3. 📄 Create Email Template:"
echo "   - Go to Email Templates"
echo "   - Create a new template"
echo "   - Use the HTML template from EMAILJS_TEMPLATE_SETUP.md"
echo "   - Note down your Template ID"
echo ""
echo "4. 🔑 Get API Keys:"
echo "   - Go to Account → API Keys"
echo "   - Copy your Public Key"
echo ""
echo "5. ⚙️  Update Environment Variables:"
echo "   - Edit your .env file with the following values:"
echo "     VITE_EMAILJS_SERVICE_ID=your_service_id"
echo "     VITE_EMAILJS_TEMPLATE_ID=your_template_id"
echo "     VITE_EMAILJS_PUBLIC_KEY=your_public_key"
echo ""
echo "6. 🚀 Deploy Supabase Edge Function:"
echo "   - Set EmailJS secrets in Supabase:"
echo "     supabase secrets set EMAILJS_SERVICE_ID=your_service_id"
echo "     supabase secrets set EMAILJS_TEMPLATE_ID=your_template_id"
echo "     supabase secrets set EMAILJS_PUBLIC_KEY=your_public_key"
echo ""
echo "   - Deploy the edge function:"
echo "     supabase functions deploy send-emailjs-notification"
echo ""
echo "7. 🗄️  Run Database Migration:"
echo "   - Apply the EmailJS migration:"
echo "     supabase db reset"
echo "     # or"
echo "     supabase migration up"
echo ""
echo "8. 🧪 Test Email Notifications:"
echo "   - Start the development server:"
echo "     npm run dev"
echo "   - Navigate to http://localhost:8080/email-test"
echo "   - Run all email notification tests"
echo ""
echo "📚 Documentation:"
echo "================="
echo "- EmailJS Template Setup: EMAILJS_TEMPLATE_SETUP.md"
echo "- Cross-Faculty Availability: CROSS_FACULTY_AVAILABILITY.md"
echo "- Project README: README.md"
echo ""
echo "🎉 Setup Complete! Follow the steps above to configure EmailJS."
echo ""
echo "💡 Pro Tips:"
echo "- Test with real email addresses to verify delivery"
echo "- Check your email service provider's spam folder"
echo "- Monitor the Supabase logs for any edge function errors"
echo "- Use the test page at /email-test to verify all scenarios"
