// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yetmpnthnalztcxfqwnq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlldG1wbnRobmFsenRjeGZxd25xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4NzU1NDEsImV4cCI6MjA2OTQ1MTU0MX0.hJSUuHl_1eb0P-xy6sSu_Dv86qTgDnn2R-RLzziIfio";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});